### PR TITLE
Add workflow to create ODB schema update PR weekly

### PR DESCRIPTION
**Pull request by hugo-vrijswijk**

### CODE REVIEW

**Comment by hugo-vrijswijk** [comment]
I'm fine making this a manual action, though making a PR automatically also notifies that there is a change, and it'll always need manual merging and releasing

**Comment by toddburnside** [comment]
> I'm fine making this a manual action, though making a PR automatically also notifies that there is a change, and it'll always need manual merging and releasing

Can it be both?

**Comment by hugo-vrijswijk** [comment]
> > I'm fine making this a manual action, though making a PR automatically also notifies that there is a change, and it'll always need manual merging and releasing
> 
> Can it be both?

Yeah there is now a schedule and a workflow_dispatch in the workflow (and for this branch, just for testing)

**Comment by toddburnside** [comment]
If there is a change in the schema, won't that often require a bump in the base version? I guess if there are only additions, maybe not?

**Comment by hugo-vrijswijk** [comment]
If there's just additions I don't think so. But that still gives a starting point (and might let people know of unintented breaking changes)

**Comment by rpiaggio** [comment]
> Reduce spamminess, but unmerged PR's _should_ just be updated when there are new changes

It would be spammy because a PR get created even if there are no changes? Or because the schema changes very frequently?

**Comment by hugo-vrijswijk** [comment]
> > Reduce spamminess, but unmerged PR's _should_ just be updated when there are new changes
> 
> It would be spammy because a PR get created even if there are no changes? Or because the schema changes very frequently?

Because of the frequent schema changes. The PR doesn't get created if there's no changes

**Comment by rpiaggio** [comment]
> Because of the frequent schema changes. The PR doesn't get created if there's no changes

Nice. I'd say go with daily. The schema is expected to become more and more stable.

**Comment by hugo-vrijswijk** [comment]
> Nice. I'd say go with daily. The schema is expected to become more and more stable.

Alright, I've changed it to daily now

**Review by toddburnside — APPROVED** [review]
LGTM

**Pull request merged**
